### ISSUE TITLE
Could not find module `discourse/components/hamburger-menu`

### ISSUE THREAD

**Issue by bzg** [ShareLex/discourse-static-pages#1]
> Uncaught Error: Could not find module `discourse/components/hamburger-menu` imported from `discourse/plugins/static-pages/discourse/initializers/static-pages-menu` Url: http://www.sharelex.org/assets/

@albanlv I have this error in http://www.sharelex.org/logs - can you help debug this?

**Comment by scttnlsn** [comment]
Looks like the Discourse plugin API has changed: https://meta.discourse.org/t/a-new-versioned-api-for-client-side-plugins/40051

This will probably need to be updated: https://github.com/ShareLex/discourse-static-pages/blob/master/assets/javascripts/discourse/initializers/static-pages-menu.js.es6

Here's an example I found using the newer APIs: https://github.com/discourse/discourse-akismet/blob/master/assets/javascripts/discourse/initializers/add-akismet-count.js.es6

**Comment by bzg** [comment]
Hi @scttnlsn, thanks for the details - can you update the plugin?

This bug has nasty side-effects such as preventing native polls from working.

Thanks in advance!

**Comment by zaiste** [comment]
@bzg @scttnlsn worked with us on this with defined scope as a _paid_ mission, if there change requests, it should be additionally priced

**Comment by bzg** [comment]
@zaiste The idea of the mission was to develop an open source module for Discourse.  I think our visions of open source diverge, but fair enough: we will ask someone else.
